server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/suitx}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# Allow CORS for local dev; tighten in prod
app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      base-url: ${OPENAI_API_BASE:https://api.openai.com/v1}
      model: ${OPENAI_MODEL:gpt-4o-mini}